Repository AY2021S1-CS2113T-W11-4/tp, pull requests merged in 2020-10, with the labels that each got.

#209 Add logging to bunnyLoader class
  src/main/java/seedu/duke/bunnylist/DeleteBunny.java
  src/main/java/seedu/duke/database/BunnyLoader.java
Labels: priority.Medium

#276 Fix Help Command
  docs/UserGuide.md
  src/main/java/seedu/duke/functions/CommandExecutor.java
  src/main/java/seedu/duke/ui/UI.java
Labels: severity.VeryLow

#277 Add Help
  data/words.txt
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#278 Add formatting for filter names
  src/main/java/seedu/duke/names/Names.java
Labels: priority.Low
